ETicket_Application/Controllers/ActorsController.cs
using ETicket_Application.Data;
using ETicket_Application.Data.ServicesInterface;
using ETicket_Application.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ETicket_Application.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorsService _service;
        public ActorsController(IActorsService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _service.GetAllAsync());
        }
        //Get: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Actor actor)
        {
            if (ModelState.IsValid)
            {
                await _service.CreateAsync(actor);
                return RedirectToAction("Index");
            }
            return View(actor);
        }

        //Get: Actors/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if(actorDetails == null)
            {
                return View("NotFound");
            }
            return View(actorDetails);
        }

        //Get: Actors/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null)
            {
                return View("NotFound");
            }
            return View(actorDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Actor actor)
        {
            if (ModelState.IsValid && actor.Id == id)
            {
                await _service.EditAsync(id, actor);
                return RedirectToAction("Index");
            }
            return View(actor);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null)
            {
                return View("NotFound");
            }
            return View(actorDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            await _service.DeleteAsync(id);
            return RedirectToAction("Index"); 
        }
    }
}

ETicket_Application/Controllers/CinemasController.cs
using ETicket_Application.Data;
using ETicket_Application.Data.ServicesInterface;
using ETicket_Application.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ETicket_Application.Controllers
{
    public class CinemasController : Controller
    {
        private readonly ICinemasService _service;
        public CinemasController(ICinemasService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _service.GetAllAsync());
        }

        //Get: Cinema/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Cinema cinema)
        {
            if (ModelState.IsValid)
            {
                await _service.CreateAsync(cinema);
                return RedirectToAction("Index");
            }
            return View(cinema);
        }

        //Get: Cinema/Details/1
        public async Task<IActionResult> Details(int id)
        {
            return View(await _service.GetByIdAsync(id));
        }

        //Get: Cinema/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("NotFound");
            return View(cinemaDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Cinema cinema)
        {
            if (ModelState.IsValid && cinema.Id == id)
            {
                await _service.EditAsync(id, cinema);
                return RedirectToAction("Index");
            }
            return View(cinema);
        }

        //Get: Cinema/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("NotFound");
            return View(cinemaDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            await _service.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

ETicket_Application/Controllers/MoviesController.cs
using ETicket_Application.Data;
using ETicket_Application.Data.ServicesInterface;
using ETicket_Application.Data.ViewModels;
using ETicket_Application.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.PortableExecutable;
using System.Threading.Tasks;

namespace ETicket_Application.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMoviesService _service;
        public MoviesController(IMoviesService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _service.GetAllAsync(x=> x.Cinema, y=> y.MovieCategory, z=> z.Producer));
        }

        public async Task<IActionResult> ListIndex()
        {
            ViewBag.Count = _service.CountAsync();
            return View(await _service.GetAllAsync(x => x.Cinema, y => y.MovieCategory, z => z.Producer));
        }
        
        public async Task<IActionResult> MoviesByProducers(int id)
        {
            ViewBag.Count = _service.CountByProducer(id);
            return View(await _service.GetMoviesByProducersAsync(id));
        }

        public async Task<IActionResult> Details(int id)
        {
            return View(await _service.GetMovieByIdAsync(id));
        }

        public async Task<IActionResult> Create()
        {
            var movieDropDOwn = await _service.GetMovieDropDownValues();
            ViewBag.Cinemas = new SelectList(movieDropDOwn.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropDOwn.Producers, "Id", "ProducerName");
            ViewBag.Actors = new SelectList(movieDropDOwn.Actors, "Id", "ActorName");
            ViewBag.Categories = new SelectList(movieDropDOwn.MovieCategories, "Id", "Category");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(MovieViewModel mv)
        {
            if (ModelState.IsValid)
            {
                await _service.AddNewMovieAsync(mv);
                return RedirectToAction("ListIndex");
            }
            var movieDropDOwn = await _service.GetMovieDropDownValues();
            ViewBag.Cinemas = new SelectList(movieDropDOwn.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropDOwn.Producers, "Id", "ProducerName");
            ViewBag.Actors = new SelectList(movieDropDOwn.Actors, "Id", "ActorName");
            ViewBag.Categories = new SelectList(movieDropDOwn.MovieCategories, "Id", "Category");
            return View(mv);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var movieDropDOwn = await _service.GetMovieDropDownValues();
            ViewBag.Cinemas = new SelectList(movieDropDOwn.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropDOwn.Producers, "Id", "ProducerName");
            ViewBag.Actors = new SelectList(movieDropDOwn.Actors, "Id", "ActorName");
            ViewBag.Categories = new SelectList(movieDropDOwn.MovieCategories, "Id", "Category");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(MovieViewModel mv)
        {
            if (ModelState.IsValid)
            {
                await _service.AddNewMovieAsync(mv);
                return RedirectToAction("ListIndex");
            }
            var movieDropDOwn = await _service.GetMovieDropDownValues();
            ViewBag.Cinemas = new SelectList(movieDropDOwn.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropDOwn.Producers, "Id", "ProducerName");
            ViewBag.Actors = new SelectList(movieDropDOwn.Actors, "Id", "ActorName");
            ViewBag.Categories = new SelectList(movieDropDOwn.MovieCategories, "Id", "Category");
            return View(mv);
        }
    }
}

ETicket_Application/Controllers/ProducersController.cs
using ETicket_Application.Data;
using ETicket_Application.Data.ServicesInterface;
using ETicket_Application.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ETicket_Application.Controllers
{
    public class ProducersController : Controller
    {
        private readonly IProducersService _service;
        public ProducersController(IProducersService service)
        {
            _service = service;
        }
        //Get: Producers/Index
        public async Task<IActionResult> Index()
        {
            return View(await _service.GetAllAsync());
        }

        //Get: Producers/Details/1
        public async Task<IActionResult> Details(int id)
        {
            return View(await _service.GetByIdAsync(id));
        }

        //Get: Producers/Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Producer producer)
        {
            if (ModelState.IsValid)
            {
                await _service.CreateAsync(producer);
                return RedirectToAction("Index");
            }
            return View(producer);
        }

        //Get: Producers/Edit/1

        public async Task<IActionResult> Edit(int id)
        {
            return View(await _service.GetByIdAsync(id));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Producer producer)
        {
            if (ModelState.IsValid && producer.Id == id)
            {
                await _service.EditAsync(id, producer);
                return RedirectToAction("Index");
            }
            return View(producer);
        }

        //Get: Producers/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            return View(await _service.GetByIdAsync(id));
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            await _service.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

ETicket_Application/Views/Movies/Create.cshtml
@model MovieViewModel
@{
    ViewData["Title"] = "Create";
}

<div class="row offset-3">
    <div class="col-md-8">
        <h1 class="display-6">Create new Movie</h1>
        <hr />
    </div>
    <div class="row">
        <div class="col-md-8 ">
            <form method="post" asp-action="Create" asp-controller="Movies">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Name" class="col-form-label"></label>
                            <input asp-for="Name" class="form-control col-4" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="StartDate" class="col-form-label"></label>
                            <input asp-for="StartDate" class="form-control col-4" type="date" />
                            <span asp-validation-for="StartDate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CinemaId" class="col-form-label"></label>
                            <select asp-for="CinemaId" asp-items="@ViewBag.Cinemas" class="form-select col-4">
                                <option selected>Select Cinema</option>
                            </select>
                            <span asp-validation-for="CinemaId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Price" class="col-form-label"></label>
                            <input asp-for="Price" class="form-control col-4" />
                            <span asp-validation-for="Price" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Image" class="col-form-label"></label>
                            <input asp-for="Image" class="form-control col-4" />
                            <span asp-validation-for="Image" class="text-danger"></span>
                        </div>

                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="MovieCategoryId" class="col-form-label"></label>
                            <select asp-for="MovieCategoryId" asp-items="@ViewBag.Categories" class="form-select">
                                <option selected>Selct Genre</option>
                            </select>
                            <span asp-validation-for="MovieCategoryId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="EndDate" class="col-form-label"></label>
                            <input asp-for="EndDate" class="form-control col-4" type="date" />
                            <span asp-validation-for="EndDate" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="ProducerId" class="col-form-label"></label>
                            <select asp-for="ProducerId" asp-items="@ViewBag.Producers" class="form-select col-4">
                                <option selected>Select Producer</option>
                            </select>
                            <span asp-validation-for="ProducerId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ActorIds" class="col-form-label"></label>
                            <select asp-for="ActorIds" asp-items="@ViewBag.Actors" class="form-select col-4" multiple>
                                <option selected>Select Actors</option>
                            </select>
                            <span asp-validation-for="ActorIds" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <label asp-for="Description" class="col-form-label"></label>
                        <textarea asp-for="Description" class="form-control col-4"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group mt-2">
                    <a asp-action="ListIndex" class="btn btn-outline-danger float-start">Cancel</a>
                    <button type="submit" class="btn btn-warning float-end">Save</button>
                </div>
            </form>
        </div>
        <div class="col-md-4 text-center mt-4">
            <img width="100%" class="imgPreviewCreate" id="ImagePreview" />
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/libs/jquery/jquery.js"></script>
    <script src="~/libs/validate/jquery.validate.js"></script>
    <script src="~/libs/unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script>
        $("#Image").on("change", function () {
            var output = document.getElementById("ImagePreview");
            output.src = $(this).val();
        })

        $(document).ready(function () {
            var output = document.getElementById('ImagePreview');
            output.src = $("#Image").val();
        })
    </script>
}

@section Styles{

    <style>
        .imgPreviewCreate {
            width: 300px;
            height: 450px;
            border: 3px solid white;
            border-radius: 3px;
            object-fit: cover;
        }
    </style>
}

ETicket_Application/Views/Movies/Details.cshtml
@model Movie
@{
    ViewData["Title"] = "Index";
}


<div class="row">
    <div class="col-md-7 offset-3">
        <div class="card mb-2" style="max-width:800px;">
            <div class="row g-0">
                <div>
                    <div class="col-md-12">
                        <div class="card-header bg-warning bg-opacity-50">
                            <h5 class="card-title">
                                @Model.Name
                                <a class="btn btn-sm btn-outline-dark float-end" title="Edit"><i class="bi bi-pencil-square"></i></a>
                            </h5>
                        </div>
                        <div>
                            <div class="row mb-1">
                                <div class="col-md-6">
                                    <img src="@Model.Image" width="100%" />
                                </div>
                                <div class="col-md-6">
                                    <div class="card-body">
                                        <p class="card-text">@Model.Description</p>
                                        <p class="card-text">
                                            <b>Cinema:</b>
                                            <a class="text-dark" asp-action="Details" asp-controller="Cinemas" asp-route-id="@Model.CinemaId">
                                                @Model.Cinema.Name
                                            </a>
                                        </p>
                                        <p class="card-text"><b>Category:</b> @Model.MovieCategory.Category</p>
                                        <p class="card-text">
                                            <b>Producer:</b>
                                            <a class="text-dark" asp-action="Details" asp-controller="Producers" asp-route-id="@Model.ProducerId">
                                                @Model.Producer.ProducerName
                                            </a>
                                        </p>
                                        <p class="card-text"><b>Start Date:</b> @Model.StartDate.ToShortDateString()</p>
                                        <p class="card-text"><b>End Date:</b> @Model.EndDate.ToShortDateString()</p>
                                        <p class="card-text">
                                            <b>Status:</b>
                                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                                            {
                                                <span class="badge bg-success text-white">AVAILABLE</span>
                                            }
                                            else if (DateTime.Now > Model.EndDate)
                                            {
                                                <span class="badge bg-danger text-white">EXPIRED</span>
                                            }
                                            else
                                            {
                                                <span class="badge bg-primary text-white">UPCOMING</span>
                                            }
                                        </p>
                                        <p class="card-text">
                                            <b>Actors:</b>
                                            <hr />
                                            <div class="row">
                                                @foreach (var a in Model.Actors_Movies)
                                                {
                                                    <div class="col-4 text-center">
                                                        <img class="img-thumbnail ms-0" src="@a.Actor.ProfilePicture" style="width:100px; height:100px; object-fit:cover" />
                                                        <br />
                                                        <a class="text-dark" asp-action="Details" asp-controller="Actors" asp-route-id="@a.ActorId">
                                                            @a.Actor.ActorName
                                                        </a>
                                                    </div>
                                                }
                                            </div>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="card-footer">
                                <p class="card-text d-flex justify-content-between">
                                    <a class="btn btn-sm btn-outline-primary" title="Back to List" asp-action="Index" asp-controller="Movies">Back</a>
                                    <span class="text-danger fw-semibold mt-sm-1">@Model.Price.ToString("BDT 0.0")</span>
                                    <a class="btn btn-sm btn-outline-warning" title="Add to cart"><i class="bi bi-cart-plus me-sm-1"></i>Add to cart</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ETicket_Application/Views/Movies/Index.cshtml
@model IEnumerable<Movie>
@{
    ViewData["Title"] = "Index";
}


<div class="row">
    @await Html.PartialAsync("_CreateNew", "Movies")
    @foreach (var m in Model)
    {
        <div class="col-md-4 col-xs-6 border-warning mb-2">
            <div class="card mb-2" style="max-width: 540px;">
                <div class="row g-0">
                    <div>
                        <div class="col-md-12">
                            <div class="card-header bg-warning bg-opacity-50">
                                <h5 class="card-title">
                                    @m.Name
                                    <a class="btn btn-sm btn-outline-dark float-end" title="Edit"><i class="bi bi-pencil-square"></i></a>
                                </h5>
                            </div>
                            <div>
                                <div class="row mb-1">
                                    <div class="col-md-6">
                                        <img src="@m.Image" width="100%" />
                                    </div>
                                    <div class="col-md-6">
                                        <div class="card-body">
                                            <p class="card-text">@m.Description</p>
                                            <p class="card-text"><b>Cinema:</b> @m.Cinema.Name</p>
                                            <p class="card-text"><b>Category:</b> @m.MovieCategory.Category</p>
                                            <p class="card-text"><b>Producer:</b> @m.Producer.ProducerName</p>
                                            <p class="card-text"><b>Start Date:</b> @m.StartDate.ToShortDateString()</p>
                                            <p class="card-text"><b>End Date:</b> @m.EndDate.ToShortDateString()</p>
                                            <p class="card-text">
                                                <b>Status:</b>
                                                @if (DateTime.Now >= m.StartDate && DateTime.Now <= m.EndDate)
                                                {
                                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                                }
                                                else if (DateTime.Now > m.EndDate)
                                                {
                                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                                }
                                                else
                                                {
                                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                                }
                                            </p>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="card-footer">
                                    <p class="card-text d-flex justify-content-between">
                                        <a class="btn btn-sm btn-outline-primary" title="See Details" asp-action="Details" asp-controller="Movies" asp-route-id="@m.Id">
                                        <i class="bi bi-eye-fill me-sm-1"></i> Details</a>
                                        <span class="text-danger fw-semibold mt-sm-1">@m.Price.ToString("BDT 0.0")</span>
                                        <a class="btn btn-sm btn-outline-warning" title="Add to cart"><i class="bi bi-cart-plus me-sm-1"></i>Add to cart</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

ETicket_Application/Views/Movies/ListIndex.cshtml
@model IEnumerable<Movie>
@{
    ViewData["Title"] = "ListIndex";
}


<div class="row">
    <h3 class="mb-3 display-6 text-dark text-center">Movies List</h3>
    <hr />
    <div class="col-2">
        <span class="fs-5">Total Movies: @ViewBag.Count</span>
    </div>
    @await Html.PartialAsync("_CreateNew", "Movies")
    <div class="col-12 d-flex justify-content-center">
        <table class="table table-hover box-shadow table-borderless ">
            <thead>
                <tr class="table-warning text-center">
                    <th>Poster</th>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Description</th>
                    <th>Producer</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Ticket Price</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var m in Model)
                {
                    <tr class="text-center align-middle">
                        <td>
                            <img src="@m.Image" class="rounded-circle img" width="50" height="50" />
                        </td>
                        <td>@m.Name</td>
                        <td>@m.MovieCategory.Category</td>
                        <td>@m.Description</td>
                        <td>
                            <a class="text-dark" asp-action="MoviesByProducers" asp-controller="Movies" asp-route-id="@m.ProducerId">@m.Producer.ProducerName</a>
                        </td>
                        <td>@m.StartDate.ToShortDateString()</td>
                        <td>@m.EndDate.ToShortDateString()</td>
                        <td>@m.Price</td>

                        <td>
                            <a asp-action="Edit" asp-controller="Movies" asp-route-id="@m.Id" class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i></a>
                            <a asp-action="Details" asp-controller="Movies" asp-route-id="@m.Id" class="btn btn-outline-info"><i class="bi bi-eye"></i></a>
                            <a asp-action="Delete" asp-controller="Movies" asp-route-id="@m.Id" class="btn btn-outline-danger"><i class="bi bi-trash"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

ETicket_Application/Views/Movies/MoviesByProducers.cshtml
@model IEnumerable<Movie>
@{
    ViewData["Title"] = "ListIndex";
}


<div class="row">
    <h3 class="mb-3 display-6 text-dark text-center">Movies List By Producer</h3>
    <hr />
    <div class="col-2">
        <span class="fs-5">Total Movies: @ViewBag.Count</span>
    </div>
    @await Html.PartialAsync("_CreateNew", "Movies")
    <div class="col-12 d-flex justify-content-center">
        <table class="table table-hover box-shadow table-borderless ">
            <thead>
                <tr class="table-warning text-center">
                    <th>Poster</th>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Description</th>
                    <th>Producer</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Ticket Price</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var m in Model)
                {
                    <tr class="text-center align-middle">
                        <td>
                            <img src="@m.Image" class="rounded-circle img" width="50" height="50" />
                        </td>
                        <td>@m.Name</td>
                        <td>@m.MovieCategory.Category</td>
                        <td>@m.Description</td>
                        <td>@m.Producer.ProducerName</td>
                        <td>@m.StartDate.ToShortDateString()</td>
                        <td>@m.EndDate.ToShortDateString()</td>
                        <td>@m.Price</td>

                        <td>
                            <a asp-action="Edit" asp-controller="Movies" asp-route-id="@m.Id" class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i></a>
                            <a asp-action="Details" asp-controller="Movies" asp-route-id="@m.Id" class="btn btn-outline-info"><i class="bi bi-eye"></i></a>
                            <a asp-action="Delete" asp-controller="Movies" asp-route-id="@m.Id" class="btn btn-outline-danger"><i class="bi bi-trash"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>